// Code generated by "stringer -type=ColorSpace -trimprefix=ColorSpace"; DO NOT EDIT.

package colorswatch

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ColorSpaceRGB-0]
	_ = x[ColorSpaceHSB-1]
	_ = x[ColorSpaceCMYK-2]
	_ = x[ColorSpaceLab-7]
	_ = x[ColorSpaceGrayscale-8]
	_ = x[ColorSpacePantone-3]
	_ = x[ColorSpaceFocoltone-4]
	_ = x[ColorSpaceTruematch-5]
	_ = x[ColorSpaceToyo-6]
	_ = x[ColorSpaceHKS-10]
}

const (
	_ColorSpace_name_0 = "RGBHSBCMYKPantoneFocoltoneTruematchToyoLabGrayscale"
	_ColorSpace_name_1 = "HKS"
)

var (
	_ColorSpace_index_0 = [...]uint8{0, 3, 6, 10, 17, 26, 35, 39, 42, 51}
)

func (i ColorSpace) String() string {
	switch {
	case i <= 8:
		return _ColorSpace_name_0[_ColorSpace_index_0[i]:_ColorSpace_index_0[i+1]]
	case i == 10:
		return _ColorSpace_name_1
	default:
		return "ColorSpace(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
