// Code generated by "stringer -type=ColorType -trimprefix=ColorType"; DO NOT EDIT.

package colorbook

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ColorTypeRGB-0]
	_ = x[ColorTypeCMYK-2]
	_ = x[ColorTypeLab-7]
}

const (
	_ColorType_name_0 = "RGB"
	_ColorType_name_1 = "CMYK"
	_ColorType_name_2 = "Lab"
)

func (i ColorType) String() string {
	switch {
	case i == 0:
		return _ColorType_name_0
	case i == 2:
		return _ColorType_name_1
	case i == 7:
		return _ColorType_name_2
	default:
		return "ColorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
